version: "3"
services:

  postgres_db:
    container_name: postgresDB
    image: postgres
    environment:
      - POSTGRES_DB=postgresDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis_server:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres-data: